### ISSUE TITLE
Unknown "document_rootwp" variable error in certain environments

### ISSUE THREAD

**Issue by drawpause** [devgeniem/wp-project#12]
Nginx gives an error `nginx: [emerg] unknown "document_rootwp" variable` when in staging environment.

**Comment by onnimonni** [comment]
This was quite misfortunate timing. Yesterday evening I pushed breaking change into the `docker-wordpress-server` and it seems to have cached that broken image for you. I noticed this after 20minutes and pushed new version.

If errors like this happen try rebuilding with `--pull` flag for the `docker build`.
