### ISSUE TITLE
Issue with development environment not responding.

### ISSUE THREAD

**Issue by zArubaru** [devgeniem/wp-project#21]
Sometimes the development freezes for a long time. With good luck it comes back up. This often happens even right after `gdev up`.

Log:
`web_1              | 2017/02/23 13:21:59 [error] 312#312: *8 connect() failed (113: No route to host) while connecting to upstream, client: 172.17.0.4, server: _, request: "GET / HTTP/1.1", subrequest: "/redis-fetch", upstream: "redis://172.17.0.8:6379", host: "hol.test"`

**Comment by villepietarinen** [comment]
deprecated issue
