### ISSUE TITLE
[Error] WordPress is not installed here: /var/www/project/web/wp

### ISSUE THREAD

**Issue by mitramejia** [devgeniem/wp-project#7]
After running `gdev up` all containers spawn beautifully but the _web_ container complains about wordpress not being installed, despite all Wordpress files existing there. 

I recreated all containers, restarted services, rebooted my machine, ran `composer update` inside contanier with no success. What could be causing this? How can it be solved?

Here's an screenshot of the current setup with the web container log
![screenshot_10_7_16__11_24_am](https://cloud.githubusercontent.com/assets/2616517/19195720/b21baef2-8c80-11e6-9598-15b193626804.jpg)

**Comment by mitramejia** [comment]
This was caused because the DNS didn't recognize the **.com** domain, as stated in your docs I must use the **.test** domain. Thank you for writing great docs

**Comment by onnimonni** [comment]
Did you run the `gdev sync` command?

**Comment by mitramejia** [comment]
Yes, I shall open a new issue since it's already working on local development, but not on production using the _Dockerfile_ included ins this project, meant for production usage.
