### ISSUE TITLE
Refactor phinx seed to not use wp-cli through system() calls.

### ISSUE THREAD

**Issue by onnimonni** [devgeniem/wp-project#8]
Our seed data file is becoming too unstable with plenty of seed data.

Seed file `db/seeds/InstallWordPressAndActivatePlugins.php` needs refactoring.

I suggest we load wp-core through:

``` php
/**
 * Load wp-core in order to use core functions
 */
require_once( dirname(__DIR__) . '/web/wp/wp-load.php' );
```

And refactoring the `run()` command to look something like this:

``` php
public function run()
    {
      wp_install();

      wp_insert_post();

      update_option();
      ...
    }
}
```

**Comment by onnimonni** [comment]
We could also have multiple smaller snippets in `db/seeds` folder.

I think that installation and plugin activation should be in one file and options could be added in another files:
```
db/seeds/addDefaultOptions.php
```

**Comment by villepietarinen** [comment]
deprecated issue. seed.sh installs core and activates plugins and creates some posts, seed.php seeds default options, navigations and pages
